# Generated by Django 5.0.6 on 2024-06-21 15:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ازمایش')),
                ('code', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=128, verbose_name='کد ازمایش')),
                ('price', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'ازمایش',
                'verbose_name_plural': 'ازمایش ها',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام بیمار')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('mobile_phone', models.CharField(max_length=11, verbose_name='همراه')),
                ('home_phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('national_id', models.CharField(default='', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='شناسه ملی معتبر نیست.', regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('insurance', models.CharField(max_length=150, verbose_name='بیمه')),
                ('supplementary_insurance', models.CharField(choices=[('YES', 'دارد'), ('NO', 'ندارد')], max_length=128, verbose_name='تکمیلی')),
                ('version_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نسخه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions_doctors', to='doctors.doctor', verbose_name='پزشک')),
                ('medical_tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptions.medicaltest', verbose_name='ازمایش')),
            ],
            options={
                'verbose_name': 'پذیرش',
                'verbose_name_plural': 'پذیرش ها',
            },
        ),
    ]
