# Generated by Django 5.0.6 on 2024-06-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='price',
            field=models.FloatField(verbose_name='قیمت'),
        ),
    ]
