# Generated by Django 5.0.6 on 2024-06-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نمایشی')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='عنوان انگلیسی')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسترسی',
                'verbose_name_plural': 'دسترسی ها',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نمایشی')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='عنوان انگلیسی')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('permissions', models.ManyToManyField(blank=True, related_name='role', to='acl.permission', verbose_name='نقش ها')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش ها',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='acl.role', verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'نقش کاربر',
                'verbose_name_plural': 'نقش کاربران',
            },
        ),
    ]
