# Generated by Django 5.0.6 on 2024-07-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='acl.permission', verbose_name='دسترسی ها'),
        ),
    ]
